[project]
name = "must-test-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.16.5",
    "fastapi[standard]==0.115.0",
]
[dependency-groups]
dev = [
    "ruff>=0.12.11",
]


[tool.ruff.lint]

select = ["E4", "E7", "E9", "F", "I"]